.PHONY: help requirements upgrade lint mypy format test docs clean \
        extract_translations compile_translations dummy_translations \
        pull_translations push_translations validate_translations \
        build_dummy_translations detect_changed_source_translations \
        test-pii test-e2e e2e-start-services e2e-stop-services selfcheck coverage \
        install_transifex_client

.DEFAULT_GOAL := help

# For opening files in a browser. Use like: $(BROWSER)relative/path/to/file.html
BROWSER := python -m webbrowser file://$(CURDIR)/

SRC_FILES_PROD = forum tests test_utils manage.py

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info
	rm -fr .pytest_cache/

requirements: ## Sync dev dependencies
	uv sync --group dev
	uv tool install tox --with tox-uv

upgrade: ## Upgrade python dependencies and regenerate uv constraints
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

lint: ## Run linting checks
	uv run tox -e quality

mypy: ## Run mypy type checks
	uv run tox -e mypy

format: ## Auto-fix formatting issues
	uv run black ${SRC_FILES_PROD}

test: ## Run unit tests
	uv run pytest

docs: ## generate Sphinx HTML documentation, including API docs
	uv run tox -e docs
	$(BROWSER)docs/_build/html/index.html

coverage: clean ## generate and view HTML coverage report
	uv run pytest --cov-report html
	$(BROWSER)htmlcov/index.html

test-pii: ## check for PII annotations on all Django models
	DJANGO_SETTINGS_MODULE=forum.settings.test \
	  uv run code_annotations django_find_annotations --config_file .pii_annotations.yml --lint --report --coverage

test-e2e: e2e-stop-services e2e-start-services ## run end-to-end tests
	uv run pytest tests/e2e

e2e-start-services: ## Start dependency containers necessary for e2e tests
	docker compose -f tests/e2e/docker-compose.yml --project-name forum_e2e up -d

e2e-stop-services: ## Stop dependency containers necessary for e2e tests
	docker compose -f tests/e2e/docker-compose.yml --project-name forum_e2e down

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

## Localization targets

extract_translations: ## extract strings to be translated, outputting .mo files
	rm -rf docs/_build
	cd forum && i18n_tool extract --no-segment

compile_translations: ## compile translation files, outputting .po files for each supported language
	cd forum && i18n_tool generate

detect_changed_source_translations:
	cd forum && i18n_tool changed

ifeq ($(OPENEDX_ATLAS_PULL),)
pull_translations: ## Pull translations from Transifex
	tx pull -t -a -f --mode reviewed --minimum-perc=1
else
# Experimental: OEP-58 Pulls translations using atlas
pull_translations:
	find forum/conf/locale -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
	atlas pull $(OPENEDX_ATLAS_ARGS) translations/forum/forum/conf/locale:forum/conf/locale
	python manage.py compilemessages

	@echo "Translations have been pulled via Atlas and compiled."
endif

push_translations: ## push source translation files (.po) from Transifex
	tx push -s

dummy_translations: ## generate dummy translation (.po) files
	cd forum && i18n_tool dummy

build_dummy_translations: extract_translations dummy_translations compile_translations ## generate and compile dummy translation files

validate_translations: build_dummy_translations detect_changed_source_translations ## validate translations

install_transifex_client: ## Install the Transifex client
	# Installing client will skip CHANGELOG and LICENSE files from git changes
	# so remind the user to commit the change first before installing client.
	git diff -s --exit-code HEAD || { echo "Please commit changes first."; exit 1; }
	curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
	git checkout -- LICENSE README.rst
